name: Deploy Vote App

on:
  workflow_dispatch:   # Only runs when you trigger it manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key from Base64
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SG_SSH_KEY_BASE64 }}" | base64 -d > $HOME/.ssh/eyek_ci
          chmod 600 $HOME/.ssh/eyek_ci
          ssh-keyscan -p ${{ secrets.SG_PORT }} ${{ secrets.SG_HOST }} >> $HOME/.ssh/known_hosts

      - name: Deploy to SiteGround (vote/)
        run: |
          rsync -avz --delete -e "ssh -i $HOME/.ssh/eyek_ci -p ${{ secrets.SG_PORT }}" \
            ./vote/ \
            ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}:${{ secrets.SG_BASE_PATH }}/vote/
