name: Deploy to SiteGround (vote.earnyourencorekaraoke.com)

on:
  push:
    branches: [ main ]
    paths:
      - 'vote/**'
      - 'screen/**'
      - 'board/**'
      - 'host/**'
      - 'admin/**'
      - 'assets/**'
      - 'reports/**'
      - '.github/workflows/deploy-vote.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH key & known_hosts (base64-safe)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/sg_deploy
          chmod 600 ~/.ssh/sg_deploy
          # show a non-sensitive fingerprint to prove the key parses
          echo "Key fingerprint:"
          ssh-keygen -lf ~/.ssh/sg_deploy
          # preload host key to avoid prompt
          ssh-keyscan -p "${{ secrets.SG_PORT }}" "${{ secrets.SG_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Connectivity smoke test (non-interactive)
        shell: bash
        run: |
          ssh -o BatchMode=yes -o ConnectTimeout=10 \
            -p "${{ secrets.SG_PORT }}" -i ~/.ssh/sg_deploy \
            "${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}" "echo OK"

      - name: Ensure remote folders exist
        shell: bash
        env:
          SG_BASE_PATH: ${{ secrets.SG_BASE_PATH }}
        run: |
          ssh -p "${{ secrets.SG_PORT }}" -i ~/.ssh/sg_deploy \
            "${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}" \
            "mkdir -p ${SG_BASE_PATH}/{vote,screen,board,host,admin,assets,reports}"

      - name: Deploy folders (vote, screen, board, host, admin, assets, reports)
        shell: bash
        env:
          SG_BASE_PATH: ${{ secrets.SG_BASE_PATH }}
        run: |
          set -euo pipefail
          for dir in vote screen board host admin assets reports; do
            if [ -d "$dir" ]; then
              echo "Deploying ./$dir -> ${SG_BASE_PATH}/$dir/"
              rsync -avz --delete \
                -e "ssh -p ${{ secrets.SG_PORT }} -i ~/.ssh/sg_deploy" \
                "$dir/" "${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}:${SG_BASE_PATH}/$dir/"
            else
              echo "Skipping $dir (no local folder)"
            fi
          done
