name: deploy-vote

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'vote/**'
      - '.github/workflows/deploy-vote.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH key & known_hosts (base64-safe)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # SiteGround host key (first connect gets tricky on runners, so pin it)
          ssh-keyscan -p 18765 gcam1050.siteground.biz >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Connectivity smoke test
        shell: bash
        env:
          SG_USER: u2212-6q1dxbl4nmbd
          SG_HOST: gcam1050.siteground.biz
        run: |
          ssh -p 18765 -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes $SG_USER@$SG_HOST 'echo OK && pwd && ls -ld ~/www/vote.earnyourencorekaraoke.com/public_html || true'

      - name: Ensure remote folders exist
        shell: bash
        env:
          SG_USER: u2212-6q1dxbl4nmbd
          SG_HOST: gcam1050.siteground.biz
          SG_BASE_PATH: /home/u2212-6q1dxbl4nmbd/www/vote.earnyourencorekaraoke.com/public_html
        run: |
          ssh -p 18765 -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes $SG_USER@$SG_HOST "
            set -e
            mkdir -p $SG_BASE_PATH/vote
          "

      - name: Deploy vote folder via rsync
        shell: bash
        env:
          SG_USER: u2212-6q1dxbl4nmbd
          SG_HOST: gcam1050.siteground.biz
          SG_BASE_PATH: /home/u2212-6q1dxbl4nmbd/www/vote.earnyourencorekaraoke.com/public_html
        run: |
          rsync -avz --delete -e "ssh -p 18765 -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes" \
            vote/  $SG_USER@$SG_HOST:$SG_BASE_PATH/vote/
