name: Deploy to SiteGround (Vote Site)

on:
  workflow_dispatch:   # ✅ manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SG_DEPLOY_KEY }}

      - name: Deploy files to SiteGround (vote subdomain only)
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            ./vote/ ./screen/ ./host/ ./board/ ./assets/ ./reports/ \
            u2212-6q1dxbl4nmbd@gcam1050.siteground.biz:/home/u2212-6q1dxbl4nmbd/www/vote.earnyourencorekaraoke.com/public_html/
