name: Deploy to SiteGround

on:
  push:
    branches: [ main ]         # change if your default branch is different
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SG_HOST: ${{ secrets.SG_HOST }}
      SG_PORT: ${{ secrets.SG_PORT }}
      SG_USER: ${{ secrets.SG_USER }}
      SG_REMOTE_PATH: ${{ secrets.SG_REMOTE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Load your private key into ssh-agent (no passphrase)
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SG_SSH_KEY }}

      # Tiny debug: verify the agent has a key
      - name: Debug ssh-agent
        run: |
          ssh-add -l || true
          mkdir -p ~/.ssh
          printf "Host *\n  StrictHostKeyChecking no\n  IdentitiesOnly yes\n" > ~/.ssh/config

      - name: Smoke test SSH (verbose)
        run: |
          ssh -vvv -p "$SG_PORT" "$SG_USER@$SG_HOST" 'echo "SSH OK on $(hostname)"; whoami; pwd'

      - name: Ensure remote path exists
        run: |
          ssh -p "$SG_PORT" "$SG_USER@$SG_HOST" "mkdir -p '$SG_REMOTE_PATH'"

      - name: Ensure subfolders (optional)
        run: |
          ssh -p "$SG_PORT" "$SG_USER@$SG_HOST" "
            mkdir -p '$SG_REMOTE_PATH/screen' \
                     '$SG_REMOTE_PATH/board'  \
                     '$SG_REMOTE_PATH/host'   \
                     '$SG_REMOTE_PATH/vote'   \
                     '$SG_REMOTE_PATH/admin'
          "

      - name: Deploy via rsync (screen/board/host/vote/admin)
        run: |
          set -e
          for d in screen board host vote admin; do
            if [ -d "$d" ]; then
              echo "== Deploying $d -> $SG_REMOTE_PATH/$d =="
              rsync -az --delete \
                -e "ssh -p $SG_PORT" \
                --exclude ".DS_Store" \
                "$d/" "$SG_USER@$SG_HOST:$SG_REMOTE_PATH/$d/"
            fi
          done
