name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SG_HOST: ${{ secrets.SG_HOST }}
      SG_PORT: ${{ secrets.SG_PORT }}
      SG_USER: ${{ secrets.SG_USER }}
      SG_BASE_PATH: ${{ secrets.SG_BASE_PATH }} # e.g. /home/u2212-6q1dxbl4nmbd/www/vote.earnyourencorekaraoke.com/public_html

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Decode your base64 private key secret into ~/.ssh/sg_deploy
      - name: Prepare SSH key & known_hosts (base64-safe)
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SG_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/sg_deploy
          chmod 600 ~/.ssh/sg_deploy
          # trust host once (avoids interactive prompt)
          ssh-keyscan -p "$SG_PORT" "$SG_HOST" >> ~/.ssh/known_hosts

      - name: Connectivity smoke test
        run: |
          ssh -p "$SG_PORT" -i ~/.ssh/sg_deploy "$SG_USER@$SG_HOST" "echo ok && whoami && pwd"

      # ✅ FIXED: one single-line command; no line breaks, no brace expansion
      - name: Ensure remote folders exist
        run: |
          ssh -p "$SG_PORT" -i ~/.ssh/sg_deploy "$SG_USER@$SG_HOST" \
            "mkdir -p '$SG_BASE_PATH/vote' '$SG_BASE_PATH/screen' '$SG_BASE_PATH/board' '$SG_BASE_PATH/host' '$SG_BASE_PATH/admin' '$SG_BASE_PATH/assets' '$SG_BASE_PATH/reports'"

      # Upload without --delete (safe)
      - name: Deploy folders (vote, screen, board, host, admin, assets, reports)
        run: |
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./vote/   "$SG_USER@$SG_HOST:$SG_BASE_PATH/vote/"
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./screen/ "$SG_USER@$SG_HOST:$SG_BASE_PATH/screen/"
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./board/  "$SG_USER@$SG_HOST:$SG_BASE_PATH/board/"
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./host/   "$SG_USER@$SG_HOST:$SG_BASE_PATH/host/"
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./admin/  "$SG_USER@$SG_HOST:$SG_BASE_PATH/admin/"
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./assets/ "$SG_USER@$SG_HOST:$SG_BASE_PATH/assets/"
          rsync -avz -e "ssh -p $SG_PORT -i ~/.ssh/sg_deploy" ./reports/ "$SG_USER@$SG_HOST:$SG_BASE_PATH/reports/"
