name: Key Doctor

on:
  workflow_dispatch:

jobs:
  check-key:
    runs-on: ubuntu-latest
    steps:
      - name: Write key from secret (strip CRLF)
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          # Write the secret, removing any Windows CRLF characters just in case
          printf '%s\n' "${{ secrets.SG_DEPLOY_KEY }}" | sed 's/\r$//' > ~/.ssh/sg_deploy
          chmod 600 ~/.ssh/sg_deploy

      - name: Inspect key file
        run: |
          echo "First line:"; head -1 ~/.ssh/sg_deploy
          echo "Last  line:"; tail -1 ~/.ssh/sg_deploy
          echo "file(1):"; file ~/.ssh/sg_deploy || true

      - name: Can ssh-keygen read it?
        run: |
          # This fails if format is wrong or key is corrupted
          ssh-keygen -y -f ~/.ssh/sg_deploy > /tmp/derived_pubkey.pub
          echo "Derived public key:"; head -1 /tmp/derived_pubkey.pub

      - name: Host reachability (no auth yet)
        run: |
          ssh-keyscan -p 18765 gcam1050.siteground.biz >> ~/.ssh/known_hosts
          echo "Known hosts added."
